import type { MenuKey } from "@/types/menuKeyType"
import type { Role } from "./profiles"

export type PermissionLevel = "none" | "view" | "manage"

export const ROLE_PERMISSIONS: Record<Role, Partial<Record<MenuKey, PermissionLevel>>> = {
  operacoes: {
    dashboard: "view",
    gestao_contas: "manage",
    transferencias: "view",
    pagamentos: "view",
    depositos_gpo: "manage",
    levantamentos: "view",
    movimentos: "view",
    meu_perfil: "view",
  },
  financeiro: {
    dashboard: "view",
    transferencias: "view",
    pagamentos: "view",
    depositos_gpo: "view",
    levantamentos: "view",
    movimentos: "view",
    relatorios: "view",
    saldo_por_usuario: "view",
    faqs: "manage",
    meu_perfil: "view",
  },
  suporte: {
    dashboard: "view",
    gestao_contas: "view",
    transferencias: "view",
    pagamentos: "view",
    levantamentos: "view",
    movimentos: "view",
    saldo_por_usuario: "view",
    faqs: "manage",
    meu_perfil: "view",
  },
  compliance: {
    dashboard: "view",
    gestao_contas: "view",
    transferencias: "view",
    pagamentos: "view",
    depositos_gpo: "view",
    levantamentos: "view",
    movimentos: "view",
    relatorios: "view",
    logs: "view",
    saldo_por_usuario: "view",
    meu_perfil: "view",
  },
  tecnologia: {
    dashboard: "view",
    logs: "view",
    permissoes: "view",
    usuarios_backoffice: "view",
    servicos: "manage",
    bancos: "manage",
    movimentos: "manage",
    meu_perfil: "view",
  },
  admin: {
    dashboard: "manage",
    gestao_contas: "manage",
    transferencias: "manage",
    pagamentos: "manage",
    depositos_gpo: "manage",
    levantamentos: "manage",
    movimentos: "manage",
    relatorios: "manage",
    logs: "manage",
    saldo_por_usuario: "manage",
    permissoes: "manage",
    usuarios_backoffice: "manage",
    servicos: "manage",
    bancos: "manage",
    campanhas: "manage",
    promocoes: "manage",
    publicidades: "manage",
    faqs: "manage",
    meu_perfil: "manage",
    gestao_de_niveis: "manage",
  },
  superadmin: {
    dashboard: "manage",
    gestao_contas: "manage",
    transferencias: "manage",
    pagamentos: "manage",
    depositos_gpo: "manage",
    levantamentos: "manage",
    movimentos: "manage",
    relatorios: "manage",
    logs: "manage",
    saldo_por_usuario: "manage",
    permissoes: "manage",
    usuarios_backoffice: "manage",
    servicos: "manage",
    bancos: "manage",
    campanhas: "manage",
    promocoes: "manage",
    publicidades: "manage",
    faqs: "manage",
    meu_perfil: "manage",
    gestao_de_niveis: "manage",
  },
}

export function canViewMenu(menuKey: MenuKey, role: Role) {
  const level = ROLE_PERMISSIONS[role]?.[menuKey]
  return level === "view" || level === "manage"
}
